[project]
name = "obsidian-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elasticsearch>=8.0.0,<9.0.0",
    "google-genai>=1.64.0",
    "kafka-python-ng>=2.2.3",
    "uvicorn>=0.41.0",
]
